main/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^login/$', views.login, name='login'),
    url(r'^signin/$', views.register, name='signin'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^user/(?P<username>\w+)/$', views.user, name='user'),
    url(r'^edit-profile/$',
        views.edit_profile, name='edit_profile'),
    url(r'^post/(?P<id>\d+)', views.post, name='post'),
    url(r'^follow/(?P<username>\w+)/$', views.follow, name='follow'),
    url(r'^unfollow/(?P<username>\w+)/$', views.unfollow, name='unfollow'),
    url(r'^followers/(?P<username>\w+)/$', views.followers, name='followers'),
]

weibo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('main.urls', namespace='main')),
    url(r'^admin/', include(admin.site.urls)),
]

main/models.py
import hashlib
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils import timezone
# Create your models here.


class Permission():
    FOLLOW = 0x01
    COMMENT = 0x02
    WRITE_ARTICLES = 0x04
    MODERATE_COMMENT = 0x08
    ADMINISTER = 0x80


class Role(models.Model):
    name = models.CharField(max_length=64)
    default = models.BooleanField(default=False)
    permission = models.IntegerField(null=True)

    @staticmethod
    def insert_roles():
        roles = {
            'User': (Permission.FOLLOW |
                     Permission.COMMENT |
                     Permission.WRITE_ARTICLES, True),
            'Moderator': (Permission.FOLLOW |
                          Permission.COMMENT |
                          Permission.WRITE_ARTICLES |
                          Permission.MODERATE_COMMENT, False),
            'Administrator': (0xff, False)
        }
        for r in roles:
            role = Role.objects.filter(name=r).first()
            if not role:
                role = Role(name=r)
            role.permission = roles[r][0]
            role.default = roles[r][1]
            role.save()

    def __str__(self):
        return self.name


class UserManager(BaseUserManager):

    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address.')

        user = self.model(
            email=self.normalize_email(email),
            username=username)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        if not email:
            raise ValueError('User must have an email address.')

        user = self.create_user(
            username='admin', email=email, password=password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    # username, password, email
    email = models.EmailField(max_length=64, blank=True, unique=True)
    username = models.CharField(max_length=30)
    date_of_birth = models.DateField(default=timezone.now)
    realname = models.CharField(max_length=64, null=True)
    location = models.CharField(max_length=64, null=True)
    about_me = models.TextField(null=True)
    role = models.ForeignKey(Role, default=2)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    follower = models.ManyToManyField(
        'self', related_name='followed', symmetrical=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def can(self, permissions):
        return (self.role.permission & permissions) == permissions

    def is_administrator(self):
        return self.can(Permission.ADMINISTER)

    def gravatar(self, size=100, default='identicon', rating='g'):
        url = 'http://www.gravatar.com/avatar'
        h = hashlib.md5(self.email.encode('utf-8')).hexdigest()
        return '{url}/{hash}?s={size}&d={default}&r={rating}'.format(
            url=url, hash=h, size=size, default=default, rating=rating)

    @staticmethod
    def generate_fake(count=100):
        from random import seed
        import forgery_py

        seed()
        for i in range(count):
            u = User(
                email=forgery_py.internet.email_address(),
                username=forgery_py.internet.user_name(),
                password=forgery_py.lorem_ipsum.word(),
                realname=forgery_py.name.full_name(),
                location=forgery_py.address.city(),
                about_me=forgery_py.lorem_ipsum.sentence(),
                date_of_birth=forgery_py.date.date(True)
            )
            u.save()

    # followed and follower
    def follow(self, user):
        if not self.is_following(user):
            self.follower.add(user)
            self.save()

    def unfollow(self, user):
        self.follower.remove(user)
        self.save()

    def is_following(self, user):
        return user in self.follower.all()

    def is_followed_by(self, user):
        return self in user.follower.all()


class Post(models.Model):
    author = models.ForeignKey(User, related_name='post')
    body = models.TextField()
    timestamp = models.DateTimeField('data published', default=timezone.now)

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.author.username

    @staticmethod
    def generate_fake(count=100):
        from random import randint, seed
        import forgery_py

        seed()
        user_count = User.objects.count()
        for i in range(count):
            u = User.objects.get(pk=randint(1, user_count))
            p = Post(
                body=forgery_py.lorem_ipsum.sentences(randint(1, 3)),
                timestamp=forgery_py.date.date(True),
                author=u)
            p.save()

main/forms.py
from django import forms
from .models import User, Post


class LoginForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }
        labels = {
            'email': 'email',
        }


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'username']


class EditProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['realname', 'location', 'about_me']

    def save(self, commit=True):
        user = super(EditProfileForm, self).save(commit=False)
        return user


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['body']

main/views.py
from django.shortcuts import render, render_to_response,\
    get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import User, Post
from .forms import LoginForm, RegistrationForm, EditProfileForm,\
    PostForm
# Create your views here.

PER_PAGE = 10  # per_page Paginator


def index(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = Post.objects.create(
                body=form.cleaned_data['body'],
                author=request.user)
            post.save()
            return HttpResponseRedirect(reverse('main:index'))
    form = PostForm()

    page = request.GET.get('page')
    paginator = Paginator(Post.objects.order_by('-timestamp'), PER_PAGE)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'main/index.html',
                  {'form': form, 'posts': posts})


def login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = auth.authenticate(email=email, password=password)
        if user:
            if user.is_active:
                auth.login(request, user)
                messages.success(request, 'Welcome!!!!!!!!!!!!!!!!')
                # return HttpResponseRedirect(reverse(index))
                return render_to_response('main/index.html',
                                          context_instance=RequestContext(request))
        else:
            messages.error(request, 'Invalid username or password!')
    form = LoginForm()
    return render(request, 'main/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(request.POST.get('password'))
            user.save()
            messages.success(request, 'Sign in has successed!!!!')
            return redirect(reverse('main:index'))
    else:
        form = RegistrationForm()
    return render(request, 'main/register.html', {'form': form})


@login_required(login_url='/login/')
def about(request):
    return HttpResponse('this is a about page.')


def logout_view(request):
    auth.logout(request)
    return render_to_response('main/index.html')


@login_required(login_url='/login/')
def user(request, username):
    try:
        user = User.objects.filter(username=username).first()
    except (KeyError, User.DoesNotExist):
        messages.error(request, 'This user does not exist!')
        return render(request, 'main/index.html')
    else:
        posts = user.post.order_by('-timestamp')
        return render(request, 'main/user.html',
                      {'user': user,
                       'gravatar': user.gravatar(size=256),
                       'posts': posts})


@login_required(login_url='/login/')
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST)
        if form.is_valid():
            request.user.realname = form.cleaned_data['realname']
            request.user.location = form.cleaned_data['location']
            request.user.about_me = form.cleaned_data['about_me']
            request.user.save()
            return HttpResponseRedirect(
                reverse('main:user', args=[request.user.username]))
    else:
        form = EditProfileForm()
    return render(request, 'main/edit_profile.html', {'form': form})


def post(request, id):
    post = get_object_or_404(Post, pk=id)
    return render(request, 'main/post.html', {'posts': [post]})


@login_required(login_url='/login/')
def follow(request, username):
    user = User.objects.filter(username=username).first()
    if request.user.is_following(user):
        messages.error(request, 'You are already following this user.')
        return redirect(reverse('main:user', kwargs={'username': username}))
    request.user.follow(user)
    messages.success(request, 'You are now following %s' % username)
    return redirect(reverse('main:user', kwargs={'username': username}))


@login_required(login_url='/login/')
def unfollow(request, username):
    user = User.objects.filter(username=username).first()
    request.user.unfollow(user)
    return redirect(reverse('main:user', kwargs={'username': username}))


@login_required(login_url='/login/')
def followers(request, username):
    user = User.objects.filter(username=username).first()
    followers = user.follower.all()
    messages.success(request, 'You are now unfollowing %s' % username)
    return render(request, 'main/followers.html', {'followers': followers})

templates/main/_posts.html
<div>
    <ul class="posts">
        {% for post in posts %}
            <li class="post">
                <div class="post-author">
                    <a href="{% url 'main:user' post.author.username %}">
                        {{ post.author.username }}
                    </a>
                </div>
                <div class="post-date">{{ post.timestamp }}</div>
                <div class="post-body">{{ post.body }}</div>
                <div class="post-footer">
                    <a href="{% url 'main:post' post.pk %}">
                        <span>Permalink</span>
                    </a>
                </div>
            </li>
        {% endfor %}
    </ul>
    <div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
        {% endif %}
    </span>
    </div>

</div>

templates/main/base.html
<html>
{% block head %}
<head>
  <title>{% block title %}Weibo{% endblock %}</title>
<head>
{% endblock head %}
<body>
  <div>微博
  <a href="{% url 'main:index' %}">首页</a>
  {% if user.is_authenticated %}
    <a href="{% url 'main:user' request.user.username %}">我的主页</a>
    <a href="{% url 'main:logout' %}">注销</a>
  {% else %}
  	<a href="{% url 'main:login' %}">登陆</a>
    <a href="{% url 'main:signin' %}">注册</a>
  {% endif %}
  </div>

  <div>
  {% if messages %}
	<ul class="messages">
	  {% for message in messages %}
	   <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	  {% endfor %}
	</ul>
  {% endif %}
  </div>
 
{% block page_content %}{% endblock %}
</body>
</html>

templates/main/edit_profile.html
{% extends "main/base.html" %}
{% block title %}
    Edit Profile
{% endblock title %}
{% block page_content %}
    <h1>Edit Your Profile</h1>  
    <div>
        <form id="edit_profile" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit">
        </form>
    </div>
{% endblock page_content %}

templates/main/followers.html
{% extends "main/base.html" %}

{% block page_content %}
<div>
    {% for follower in followers %}
    <a href="{% url 'main:user' follower.username %}">{{ follower.username }}</a>
    {% endfor %}
</div>
{% endblock page_content %}

templates/main/index.html
{% extends 'main/base.html' %}

{% block page_content %}
<h1>Hello,{% if user.is_authenticated %}{{ user.username }}{% else %}Stringer{% endif %}</h1>
{% if user.is_authenticated %}
<div>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="submit">
    </form>
</div>
{% endif %}
{% include "main/_posts.html" %}
{% endblock %}

templates/main/login.html
{% extends "main/base.html" %}
{% block title %}Weibo-Login{% endblock %}
{% block page_content %}
<h1>Sign In</h1>
<div>
<form id='login' method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
</div>
{% endblock %}

templates/main/post.html
{% extends "main/base.html" %}
{% block title %}
    Weibo - Post   
{% endblock title %}
{% block page_content %}
    {% include "main/_posts.html" %}    
{% endblock page_content %}

templates/main/register.html
{% extends "main/base.html" %}
{% block title %}Weibo-Register{% endblock %}
{% block page_content %}
<h1>Sign In</h1>
<div>
<form id="register" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="注册">
</form>
</div>
{% endblock %}

templates/main/user.html
{% extends "main/base.html" %}

{% block page_content %}
<div class="page-header">
	<img src="{{ gravatar }}">	
	<div class="profile-header">
		<h1>{{ user.username }}</h1>
		{% if user.name and user.location %}
		<p>
			{% if user.name %}{{ user.name }}<br>{% endif %}
			{% if user.location %}
				From {{ user.location }}<br>	
			{% endif %}
		</p>
		{% endif %}
         {% if user.is_administrator %}
        <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
        {% endif %}
        {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
        <p>
            Member since {{ user.date_of_birth }}.<br>
            Last seen {{ user.last_login }}.</p>
        <p>
            {% if user == request.user %}
            <a class="edit_profile" href="{% url 'main:edit_profile' %}">Edit Profile</a>
            {% endif %}
            {% if user.is_administrator %}
            <a class="" href="">Edit Profile [Admin]</a>
            {% endif %}
        </p>
        {% load follow_tags %}
        {% user_can_follow request.user as permission%}
        {% if user != request.user and permission%}
            {% is_following request.user user as is_follow %}
            {% if not is_follow %}
                <a href="{% url 'main:follow' username=user.username %}">Follow</a> 
            {% else %}
                <a href="{% url 'main:unfollow' username=user.username %}">Unfollow</a>
            {% endif %}
        {% endif %}
        <a href="{% url 'main:followers' username=user.username %}">Followers: <span>Followers {% follower_count user %}</span></a>
    </div>
</div>
<h3>Posts by {{ user.username }}</h3>
{% include "main/_posts.html" %}
{% endblock page_content %}